[project]
name = "topn-sigma-generation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "hf-xet>=1.1.5",
    "torch>=2.7.1",
    "transformers>=4.54.1",
]
